name: Publish Container Image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False
  workflow_call:
    inputs:
      image_version:
        description: "Image version"
        default: "dev"
        type: string
        required: False

jobs:
  publish_container_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release tag
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
        ref: ${{ inputs.image_version }}

    - name: Set default Python version
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.12'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

    - name: Login to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm/v8
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-api:${{ inputs.image_version }}
        build-args: |
          RELEASE_VERSION=${{ inputs.image_version }}
